version: "3.7"
services:
  backend:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: here
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev