version: "3.9"
services:
  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql-db
      DB_ENV: dev

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: here
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev