name: Update Docker Image in DockerHub

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag blog-app:latest
    
    - name: Push image to docker hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog-app:latest
