name: Update Docker Image in DockerHub

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: print ls
      run: ls
    - name: Build and Tag Docker Image
      run: docker build -t blog-app . && docker tag blog-app serhhatsari/blog-app:latest
      
    - name: Push Docker Image
      run: docker push serhhatsari/blog-app:latest
